/// <reference types="npm:@types/react@18.3.1" />

import * as React from 'npm:react@18.3.1'

import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Html,
  Img,
  Preview,
  Text,
  Section,
  Hr,
} from 'npm:@react-email/components@0.0.22'
import type { TemplateEntry } from './registry.ts'

const SITE_NAME = 'CossInfo'
const LOGO_URL = 'https://gekhjpoihyiylonhlbfy.supabase.co/storage/v1/object/public/store-profiles/email-assets/logo.svg'

interface StockReportProps {
  storeName?: string
  storeId?: string
  weekDate?: string
  reportType?: string
  totalItems?: number
  downloadUrl?: string
  generatedBy?: string
}

const StockReportEmail = ({
  storeName,
  storeId,
  weekDate,
  reportType,
  totalItems,
  downloadUrl,
  generatedBy,
}: StockReportProps) => (
  <Html lang="en" dir="ltr">
    <Head />
    <Preview>Stock Report — {weekDate ?? 'Weekly'} | {SITE_NAME}</Preview>
    <Body style={main}>
      <Container style={container}>
        <Img src={LOGO_URL} alt="CossInfo" width="120" height="40" style={logo} />
        <Heading style={h1}>Stock Report Ready</Heading>
        <Text style={text}>
          Your <strong>{reportType === 'simple' ? 'Order Summary' : 'Full Stock Report'}</strong> has been generated
          {storeName ? ` for ${storeName}` : ''}{storeId ? ` (${storeId})` : ''}.
        </Text>
        <Section style={detailsBox}>
          <Text style={detailLabel}>Week: <strong>{weekDate ?? '—'}</strong></Text>
          <Text style={detailLabel}>Report Type: <strong>{reportType === 'simple' ? 'Simple Order Summary' : 'Full Report'}</strong></Text>
          {totalItems !== undefined && (
            <Text style={detailLabel}>Total Items: <strong>{totalItems}</strong></Text>
          )}
          {generatedBy && (
            <Text style={detailLabel}>Generated By: <strong>{generatedBy}</strong></Text>
          )}
        </Section>
        {downloadUrl && (
          <Section style={{ textAlign: 'center' as const, margin: '28px 0' }}>
            <Button style={button} href={downloadUrl}>
              Download PDF Report
            </Button>
          </Section>
        )}
        <Hr style={hr} />
        <Text style={footer}>
          This is an automated email from {SITE_NAME}. The download link expires in 7 days.
        </Text>
      </Container>
    </Body>
  </Html>
)

export const template = {
  component: StockReportEmail,
  subject: (data: Record<string, any>) =>
    `Stock Report — ${data.weekDate ?? 'Weekly'} | ${data.reportType === 'simple' ? 'Order Summary' : 'Full Report'}`,
  displayName: 'Stock report PDF',
  previewData: {
    storeName: 'Demo Store',
    storeId: 'STORE-0001',
    weekDate: '2026-W14',
    reportType: 'full',
    totalItems: 42,
    downloadUrl: 'https://example.com/report.pdf',
    generatedBy: 'admin@example.com',
  },
} satisfies TemplateEntry

const main = { backgroundColor: '#ffffff', fontFamily: "'Inter', Arial, sans-serif" }
const container = { padding: '20px 25px', maxWidth: '520px' }
const logo = { margin: '0 0 24px' }
const h1 = { fontSize: '22px', fontWeight: 'bold' as const, color: '#2a2563', margin: '0 0 20px' }
const text = { fontSize: '14px', color: '#596066', lineHeight: '1.5', margin: '0 0 20px' }
const detailsBox = {
  backgroundColor: '#f4f3ff',
  borderRadius: '8px',
  padding: '16px 20px',
  margin: '0 0 20px',
}
const detailLabel = { fontSize: '13px', color: '#4a4a6a', margin: '4px 0', lineHeight: '1.6' }
const button = {
  backgroundColor: '#2d2b7f',
  color: '#ffffff',
  fontSize: '14px',
  fontWeight: 'bold' as const,
  padding: '12px 28px',
  borderRadius: '6px',
  textDecoration: 'none',
}
const hr = { borderColor: '#eee', margin: '24px 0' }
const footer = { fontSize: '12px', color: '#999999', margin: '0' }
