"""
Generates docs/backend-migration-tasks.csv and backend-migration-tasks.xlsx.

Stack target: NestJS + Prisma + PostgreSQL (full schema + all existing rows migrated).

Usage:
  pip install openpyxl
  python docs/generate_migration_workbook.py
"""
from __future__ import annotations

import csv
from pathlib import Path

DOCS = Path(__file__).resolve().parent

# Engineering hours per task — AI-assisted baseline (Cursor/LLM for analysis, codegen, refactors, tests).
# Not padded for “worst case”; assumes you iterate with AI and review yourself. Ops/cutover tasks stay somewhat higher where tools cannot replace judgment.
# Adjust if mostly manual: multiply ~1.3–1.8.
_ROWS_RAW: list[dict[str, str]] = [
    # Phase 0 - Planning
    {
        "Task_ID": "MIG-001",
        "Phase": "Planning",
        "Area": "Program",
        "Task_Title": "ADR: NestJS + Prisma + PostgreSQL",
        "Description": "Lock stack: NestJS for HTTP/WebSocket APIs, Prisma as ORM and migration tool for PostgreSQL only, target hosting for API and DB. Document versions (Node LTS, Nest, Prisma). Out of scope: MySQL unless separate ADR.",
        "Acceptance_Criteria": "ADR or one-pager committed; team agrees; no ambiguous ORM/DB choice.",
        "Priority": "P0",
        "Dependencies": "",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-002",
        "Phase": "Planning",
        "Area": "Security",
        "Task_Title": "Secrets and key management",
        "Description": "DATABASE_URL for Prisma (server only), JWT keys, PayPal, SMTP, SMS, S3. Nest ConfigModule + env validation. Never expose DB URL to Vite.",
        "Acceptance_Criteria": "Checklist of secrets; .env.example for API without real values; frontend only VITE_API_URL and public keys.",
        "Priority": "P0",
        "Dependencies": "MIG-001",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-003",
        "Phase": "Planning",
        "Area": "Inventory",
        "Task_Title": "Inventory Supabase usage in frontend",
        "Description": "List files using supabase client: auth, from(), rpc(), functions.invoke(), storage, realtime channels.",
        "Acceptance_Criteria": "Matrix: file path, call type, replacement Nest route or WS event.",
        "Priority": "P0",
        "Dependencies": "",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-004",
        "Phase": "Planning",
        "Area": "Inventory",
        "Task_Title": "Inventory Edge Functions and cron",
        "Description": "Map each supabase/functions/* to future Nest module (controller + service); note env vars and triggers.",
        "Acceptance_Criteria": "All functions covered; none orphaned.",
        "Priority": "P0",
        "Dependencies": "",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-005",
        "Phase": "Planning",
        "Area": "Inventory",
        "Task_Title": "RPCs, SQL functions, and RLS inventory",
        "Description": "List supabase.rpc calls and SQL functions in migrations; extract RLS policies per table. Plan Prisma-level authorization (guards) replacing RLS.",
        "Acceptance_Criteria": "RPC matrix with parameters; RLS rules summarized; has_role and other security paths mapped to Nest guards.",
        "Priority": "P1",
        "Dependencies": "",
        "Owner": "",
        "Status": "Not_Started",
    },
    # Phase 1 - Database: target Postgres, full schema, full data
    {
        "Task_ID": "MIG-006",
        "Phase": "Database",
        "Area": "Infrastructure",
        "Task_Title": "Provision target PostgreSQL",
        "Description": "Create production-grade Postgres (RDS, Cloud SQL, managed K8s, or self-hosted). Configure backups, TLS, extensions needed by schema (uuid, pgcrypto, etc.), connection limits.",
        "Acceptance_Criteria": "Connection from bastion or CI works with SSL; backup window defined; DATABASE_URL format documented for Prisma.",
        "Priority": "P0",
        "Dependencies": "MIG-001",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-007",
        "Phase": "Database",
        "Area": "Schema",
        "Task_Title": "Deploy full SQL schema to target",
        "Description": "Replay supabase/migrations in order on empty DB, OR pg_dump --schema-only from Supabase and restore to target. Include public app tables, types, indexes, constraints, SQL functions used by RPCs. Exclude or separately handle Supabase auth/storage extensions if not cloning auth schema.",
        "Acceptance_Criteria": "prisma db execute or psql: no errors; \\dt lists expected tables; functions exist for RPC parity plan.",
        "Priority": "P0",
        "Dependencies": "MIG-006",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-008",
        "Phase": "Database",
        "Area": "Data",
        "Task_Title": "Migrate ALL existing rows (bulk copy)",
        "Description": "Full data migration: pg_dump --data-only from Supabase (or provider backup restore), OR logical replication, OR table-ordered COPY with FK checks deferred. Include every business table and large tables (orders, logs, email state). Plan maintenance window or brief read-only on source. After load: run ANALYZE; fix sequences with setval to max(id).",
        "Acceptance_Criteria": "Per-table row count matches source (automated diff); random FK spot-checks pass; sequences produce new IDs without collision.",
        "Priority": "P0",
        "Dependencies": "MIG-007",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-009",
        "Phase": "Database",
        "Area": "Data",
        "Task_Title": "Post-migration data validation",
        "Description": "Script comparing source Supabase vs target: counts, checksums on critical tables, max timestamps. Document acceptable deltas (e.g. excluded auth schema).",
        "Acceptance_Criteria": "Signed validation report; stakeholders approve before API cutover.",
        "Priority": "P0",
        "Dependencies": "MIG-008",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-010",
        "Phase": "Database",
        "Area": "Schema",
        "Task_Title": "Dry run on staging clone",
        "Description": "Repeat MIG-007–MIG-009 against staging Postgres; rehearse timing and rollback (drop schema / restore snapshot).",
        "Acceptance_Criteria": "Staging holds full schema + representative or full copy; runbook updated with actual durations.",
        "Priority": "P0",
        "Dependencies": "MIG-009",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-011",
        "Phase": "Database",
        "Area": "Auth",
        "Task_Title": "User identity migration off Supabase Auth",
        "Description": "Export or map auth.users to application user table: preserve UUIDs where stores.user_id references them OR one-time relink. Password: export bcrypt hashes if Supabase allows or force password reset. MFA factors: re-enroll in Nest flow.",
        "Acceptance_Criteria": "All active users can authenticate via new Nest auth; FK from stores to user ids valid; documented exceptions.",
        "Priority": "P0",
        "Dependencies": "MIG-008",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-012",
        "Phase": "Database",
        "Area": "Storage",
        "Task_Title": "Migrate Storage files (store-profiles bucket)",
        "Description": "Copy objects from Supabase Storage to S3-compatible bucket; preserve paths or update stores.profile_picture_url in bulk. Script with retry and verification.",
        "Acceptance_Criteria": "Object count/size matches or URLs updated and images load from new base URL.",
        "Priority": "P0",
        "Dependencies": "MIG-008",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-013",
        "Phase": "Prisma",
        "Area": "Prisma",
        "Task_Title": "prisma db pull (introspect target DB)",
        "Description": "Point DATABASE_URL at migrated Postgres; run prisma db pull to generate models from live schema. Review public schema only; ignore supabase internal schemas unless needed.",
        "Acceptance_Criteria": "schema.prisma generated; prisma validate passes; no accidental drop of tables.",
        "Priority": "P0",
        "Dependencies": "MIG-007",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-014",
        "Phase": "Prisma",
        "Area": "Prisma",
        "Task_Title": "Hand-tune Prisma schema",
        "Description": "Fix @@map/@map for snake_case, relation names, enums, Json fields, Unsupported types. Add indexes in Prisma if missing. Document views: use prisma.$queryRaw or migrate to tables.",
        "Acceptance_Criteria": "prisma generate succeeds; Prisma Client typings usable in Nest services; team review complete.",
        "Priority": "P0",
        "Dependencies": "MIG-013",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-015",
        "Phase": "Prisma",
        "Area": "Prisma",
        "Task_Title": "Prisma Migrate baseline for future changes",
        "Description": "Brownfield: baseline existing DB — prisma migrate diff or documented initial migration marking current state; from then on use prisma migrate dev/deploy for schema changes only (no drift from manual SQL without Prisma).",
        "Acceptance_Criteria": "CI applies migrations to empty test DB OR migrate deploy is no-op on prod clone; drift detection documented.",
        "Priority": "P1",
        "Dependencies": "MIG-014",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-016",
        "Phase": "Prisma",
        "Area": "Prisma",
        "Task_Title": "Seed script (optional) for dev",
        "Description": "prisma/seed.ts for local dev subset; never required for prod (prod uses real migrated data).",
        "Acceptance_Criteria": "npm run prisma:seed creates minimal dev data for Nest local run.",
        "Priority": "P2",
        "Dependencies": "MIG-014",
        "Owner": "",
        "Status": "Not_Started",
    },
    # Phase 2 - NestJS + Prisma application shell
    {
        "Task_ID": "MIG-020",
        "Phase": "Backend",
        "Area": "NestJS",
        "Task_Title": "Bootstrap NestJS project",
        "Description": "nest new or monorepo app; ConfigModule, ValidationPipe, global exception filter, health controller (/health), structured logging (pino), Swagger optional.",
        "Acceptance_Criteria": "GET /health 200; lint/test pipeline green; Dockerfile optional.",
        "Priority": "P0",
        "Dependencies": "MIG-001",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-021",
        "Phase": "Backend",
        "Area": "Prisma",
        "Task_Title": "PrismaService and Nest integration",
        "Description": "Official pattern: PrismaService extends PrismaClient, onModuleInit connect, onModuleDestroy disconnect; global module or per-request as needed. Unit test with test DB or docker-compose Postgres.",
        "Acceptance_Criteria": "Any module can inject PrismaService; e2e test runs query against test DB; CI runs prisma generate.",
        "Priority": "P0",
        "Dependencies": "MIG-014",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-022",
        "Phase": "Backend",
        "Area": "Security",
        "Task_Title": "CORS and rate limiting",
        "Description": "@nestjs/throttler on auth/OTP; CORS for Vite origins.",
        "Acceptance_Criteria": "Preflight OK; brute-force OTP returns 429 in test.",
        "Priority": "P1",
        "Dependencies": "MIG-020",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-023",
        "Phase": "Backend",
        "Area": "NestJS",
        "Task_Title": "Feature module layout",
        "Description": "Organize AuthModule, StoresModule, OrdersModule, etc.; each service uses PrismaService; DTOs with class-validator.",
        "Acceptance_Criteria": "Architecture diagram or README; no circular deps.",
        "Priority": "P1",
        "Dependencies": "MIG-021",
        "Owner": "",
        "Status": "Not_Started",
    },
    # Phase 3 - Auth
    {
        "Task_ID": "MIG-030",
        "Phase": "Auth",
        "Area": "Auth",
        "Task_Title": "Registration and password login (Prisma users)",
        "Description": "Nest guards + JWT; bcrypt/argon2; user rows in Postgres via Prisma; map user id to stores.user_id.",
        "Acceptance_Criteria": "E2E: register, login, JWT valid; Prisma shows user row.",
        "Priority": "P0",
        "Dependencies": "MIG-011",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-031",
        "Phase": "Auth",
        "Area": "Auth",
        "Task_Title": "Email OTP login and verification",
        "Description": "Replace Supabase OTP with Nest endpoints; store OTP in customer_otp_codes or equivalent via Prisma.",
        "Acceptance_Criteria": "Flows match Login, StoreRegistration, ForgotPassword UX contract.",
        "Priority": "P0",
        "Dependencies": "MIG-030",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-032",
        "Phase": "Auth",
        "Area": "Auth",
        "Task_Title": "Session refresh and logout",
        "Description": "Refresh tokens stored in DB or Redis; Nest endpoints for refresh/logout.",
        "Acceptance_Criteria": "Token rotation works; logout invalidates refresh.",
        "Priority": "P0",
        "Dependencies": "MIG-030",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-033",
        "Phase": "Auth",
        "Area": "Auth",
        "Task_Title": "Password update and reset",
        "Description": "Secure reset tokens in DB (Prisma); update password hashes.",
        "Acceptance_Criteria": "Reset flow E2E; tokens single-use.",
        "Priority": "P0",
        "Dependencies": "MIG-031",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-034",
        "Phase": "Auth",
        "Area": "Auth",
        "Task_Title": "Admin MFA (replace Supabase MFA)",
        "Description": "TOTP/WebAuthn in Nest; Prisma for factors if stored.",
        "Acceptance_Criteria": "AdminLogin parity; cannot bypass MFA for admin role.",
        "Priority": "P0",
        "Dependencies": "MIG-030",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-035",
        "Phase": "Auth",
        "Area": "Auth",
        "Task_Title": "Roles and has_role replacement",
        "Description": "Prisma queries to user_roles; RolesGuard on admin controllers.",
        "Acceptance_Criteria": "Non-admin JWT rejected; unit tests on guard.",
        "Priority": "P0",
        "Dependencies": "MIG-030",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-036",
        "Phase": "Auth",
        "Area": "Auth",
        "Task_Title": "Lovable cloud-auth integration",
        "Description": "integrations/lovable/index.ts: pass Nest JWT/session or deprecate.",
        "Acceptance_Criteria": "Documented behavior; no broken dev flow.",
        "Priority": "P2",
        "Dependencies": "MIG-032",
        "Owner": "",
        "Status": "Not_Started",
    },
    # Phase 4 - Domain APIs (Prisma in services)
    {
        "Task_ID": "MIG-040",
        "Phase": "Domain_API",
        "Area": "Stores",
        "Task_Title": "Stores CRUD and generate_store_id",
        "Description": "Nest service with Prisma transactions; port generate_store_id logic from SQL or app layer.",
        "Acceptance_Criteria": "Parity with supabase-store and AuthContext store creation.",
        "Priority": "P0",
        "Dependencies": "MIG-021",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-041",
        "Phase": "Domain_API",
        "Area": "Stores",
        "Task_Title": "check_store_duplicate endpoint",
        "Description": "POST; Prisma query matching RPC behavior.",
        "Acceptance_Criteria": "Same duplicate detection as current RPC tests.",
        "Priority": "P0",
        "Dependencies": "MIG-040",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-042",
        "Phase": "Domain_API",
        "Area": "Products",
        "Task_Title": "Global/store products and portfolio APIs",
        "Description": "Prisma for global_products, store_products, store_portfolios, stock_entries.",
        "Acceptance_Criteria": "Admin CRUD; FK integrity.",
        "Priority": "P0",
        "Dependencies": "MIG-040",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-043",
        "Phase": "Domain_API",
        "Area": "Orders",
        "Task_Title": "Customer orders and notifications",
        "Description": "Prisma for customer_orders, store_notifications; scoped by store.",
        "Acceptance_Criteria": "EmployeeDashboard operations covered.",
        "Priority": "P0",
        "Dependencies": "MIG-040",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-044",
        "Phase": "Domain_API",
        "Area": "Orders",
        "Task_Title": "Public order RPCs as REST",
        "Description": "Implement former RPCs via Prisma/raw SQL in service: get_public_store_by_slug, slots, qr products, validate customer, order status.",
        "Acceptance_Criteria": "StoreOrder works against Nest API only.",
        "Priority": "P0",
        "Dependencies": "MIG-043",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-045",
        "Phase": "Domain_API",
        "Area": "Settings",
        "Task_Title": "Store customers and time slots",
        "Description": "Prisma CRUD for store_customers, store_time_slots.",
        "Acceptance_Criteria": "Settings.tsx parity.",
        "Priority": "P0",
        "Dependencies": "MIG-040",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-046",
        "Phase": "Domain_API",
        "Area": "Support",
        "Task_Title": "Support tickets and messages",
        "Description": "Prisma for support_tickets, support_messages.",
        "Acceptance_Criteria": "SupportChatbot + AdminSupportPanel parity.",
        "Priority": "P1",
        "Dependencies": "MIG-040",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-047",
        "Phase": "Domain_API",
        "Area": "Community",
        "Task_Title": "Community chat REST",
        "Description": "Prisma for community_channels, community_messages.",
        "Acceptance_Criteria": "Polling OK until realtime.",
        "Priority": "P1",
        "Dependencies": "MIG-040",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-048",
        "Phase": "Domain_API",
        "Area": "Admin",
        "Task_Title": "Audit and billing reads",
        "Description": "Prisma for audit_logs, coupons, store_subscriptions, webhook_logs, invoices.",
        "Acceptance_Criteria": "Admin billing and revenue panels load.",
        "Priority": "P1",
        "Dependencies": "MIG-035",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-049",
        "Phase": "Domain_API",
        "Area": "Feedback",
        "Task_Title": "Feedback API",
        "Description": "Prisma feedback table.",
        "Acceptance_Criteria": "AppHeader feedback path works.",
        "Priority": "P2",
        "Dependencies": "MIG-021",
        "Owner": "",
        "Status": "Not_Started",
    },
    # Phase 5 - Integrations
    {
        "Task_ID": "MIG-050",
        "Phase": "Integrations",
        "Area": "Email",
        "Task_Title": "Transactional email in Nest",
        "Description": "Services + queues; Prisma for email logs/state; port Edge templates.",
        "Acceptance_Criteria": "Staging emails send; idempotent queue.",
        "Priority": "P0",
        "Dependencies": "MIG-020",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-051",
        "Phase": "Integrations",
        "Area": "Email",
        "Task_Title": "Unsubscribe and suppression",
        "Description": "Controllers for unsubscribe/suppression; Prisma for tokens/suppressed_emails.",
        "Acceptance_Criteria": "Unsubscribe.tsx points to Nest; secured.",
        "Priority": "P0",
        "Dependencies": "MIG-050",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-052",
        "Phase": "Integrations",
        "Area": "OTP",
        "Task_Title": "Customer OTP send/verify",
        "Description": "Nest + Prisma customer_otp_codes.",
        "Acceptance_Criteria": "Settings customer OTP flow E2E.",
        "Priority": "P0",
        "Dependencies": "MIG-045",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-053",
        "Phase": "Integrations",
        "Area": "SMS",
        "Task_Title": "Order SMS",
        "Description": "Port send-order-sms; call from order status service.",
        "Acceptance_Criteria": "Sandbox SMS or logged success.",
        "Priority": "P1",
        "Dependencies": "MIG-043",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-054",
        "Phase": "Integrations",
        "Area": "PayPal",
        "Task_Title": "PayPal checkout in Nest",
        "Description": "Controller/service; Prisma for subscriptions/invoices; update PayPalCheckout + Settings URLs to Nest.",
        "Acceptance_Criteria": "Sandbox end-to-end; webhooks to Nest.",
        "Priority": "P0",
        "Dependencies": "MIG-020",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-055",
        "Phase": "Integrations",
        "Area": "Orders",
        "Task_Title": "notify-store-order",
        "Description": "Nest service calling email/SMS.",
        "Acceptance_Criteria": "New order notifies store like today.",
        "Priority": "P0",
        "Dependencies": "MIG-050",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-056",
        "Phase": "Integrations",
        "Area": "Billing",
        "Task_Title": "check-subscriptions cron",
        "Description": "@nestjs/schedule or external cron hitting secured endpoint.",
        "Acceptance_Criteria": "Runs on schedule; logs errors.",
        "Priority": "P1",
        "Dependencies": "MIG-054",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-057",
        "Phase": "Integrations",
        "Area": "OTP",
        "Task_Title": "Registration OTP",
        "Description": "If distinct from general OTP, port to Nest.",
        "Acceptance_Criteria": "StoreRegistration completes.",
        "Priority": "P1",
        "Dependencies": "MIG-031",
        "Owner": "",
        "Status": "Not_Started",
    },
    # Phase 6 - Realtime
    {
        "Task_ID": "MIG-060",
        "Phase": "Realtime",
        "Area": "Realtime",
        "Task_Title": "WebSocket gateway (Nest)",
        "Description": "@nestjs/websockets or socket.io; JWT on handshake; event names for orders/notifications/support/community.",
        "Acceptance_Criteria": "Design doc + PoC broadcast.",
        "Priority": "P1",
        "Dependencies": "MIG-032",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-061",
        "Phase": "Realtime",
        "Area": "Realtime",
        "Task_Title": "Replace Supabase channels in frontend",
        "Description": "Connect to Nest WS; remove supabase.channel.",
        "Acceptance_Criteria": "<1s latency staging; reconnect OK.",
        "Priority": "P1",
        "Dependencies": "MIG-060",
        "Owner": "",
        "Status": "Not_Started",
    },
    # Phase 7 - Storage (API)
    {
        "Task_ID": "MIG-070",
        "Phase": "Storage",
        "Area": "Files",
        "Task_Title": "Upload API and S3 integration in Nest",
        "Description": "Multipart or signed URL; update profile_picture_url via Prisma. Align with MIG-012 migrated objects.",
        "Acceptance_Criteria": "New uploads work post-cutover; public URLs consistent.",
        "Priority": "P0",
        "Dependencies": "MIG-020",
        "Owner": "",
        "Status": "Not_Started",
    },
    # Phase 8 - Frontend
    {
        "Task_ID": "MIG-080",
        "Phase": "Frontend",
        "Area": "Client",
        "Task_Title": "API client (VITE_API_URL)",
        "Description": "fetch/axios to Nest; Bearer JWT; no Supabase env in prod.",
        "Acceptance_Criteria": "Single client module; typed errors.",
        "Priority": "P0",
        "Dependencies": "MIG-020",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-081",
        "Phase": "Frontend",
        "Area": "Client",
        "Task_Title": "Migrate auth pages and AuthContext",
        "Description": "Remove supabase.auth; call Nest.",
        "Acceptance_Criteria": "QA auth flows; no supabase in auth files.",
        "Priority": "P0",
        "Dependencies": "MIG-030",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-082",
        "Phase": "Frontend",
        "Area": "Client",
        "Task_Title": "Replace lib/supabase-store",
        "Description": "api/store.ts calling Nest; Prisma-backed routes.",
        "Acceptance_Criteria": "No supabase imports in store module.",
        "Priority": "P0",
        "Dependencies": "MIG-040",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-083",
        "Phase": "Frontend",
        "Area": "Client",
        "Task_Title": "Migrate Settings and EmployeeDashboard",
        "Description": "Includes PayPal, OTP invokes, uploads to Nest.",
        "Acceptance_Criteria": "Checklist sign-off.",
        "Priority": "P0",
        "Dependencies": "MIG-045",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-084",
        "Phase": "Frontend",
        "Area": "Client",
        "Task_Title": "Migrate StoreOrder and StoreRegistration",
        "Description": "Public flows to Nest.",
        "Acceptance_Criteria": "E2E staging.",
        "Priority": "P0",
        "Dependencies": "MIG-044",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-085",
        "Phase": "Frontend",
        "Area": "Client",
        "Task_Title": "Migrate admin UI components",
        "Description": "AdminDashboard, panels, analytics, PayPal, chatbot.",
        "Acceptance_Criteria": "No supabase in listed components.",
        "Priority": "P0",
        "Dependencies": "MIG-048",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-086",
        "Phase": "Frontend",
        "Area": "Client",
        "Task_Title": "Wire ResetPassword route in App.tsx",
        "Description": "If product needs /reset-password.",
        "Acceptance_Criteria": "Route works with Nest reset token.",
        "Priority": "P2",
        "Dependencies": "MIG-033",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-087",
        "Phase": "Frontend",
        "Area": "Client",
        "Task_Title": "Remove @supabase/supabase-js",
        "Description": "Delete client wrapper; clean env.",
        "Acceptance_Criteria": "Build passes; grep no supabase.",
        "Priority": "P1",
        "Dependencies": "MIG-085",
        "Owner": "",
        "Status": "Not_Started",
    },
    # Phase 9 - QA and cutover
    {
        "Task_ID": "MIG-090",
        "Phase": "QA",
        "Area": "Testing",
        "Task_Title": "API contract tests (Nest + Prisma test DB)",
        "Description": "Jest + supertest or Pact; prisma migrate reset for CI DB.",
        "Acceptance_Criteria": "CI green: auth, orders, admin denial.",
        "Priority": "P1",
        "Dependencies": "MIG-043",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-091",
        "Phase": "QA",
        "Area": "Testing",
        "Task_Title": "E2E against staging",
        "Description": "Playwright/Cypress full journeys on Vite + Nest + migrated DB.",
        "Acceptance_Criteria": "Nightly green on staging.",
        "Priority": "P1",
        "Dependencies": "MIG-084",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-092",
        "Phase": "Cutover",
        "Area": "Ops",
        "Task_Title": "Production cutover runbook",
        "Description": "Final incremental data sync if needed (delta after MIG-008); DNS to Nest; VITE_API_URL; freeze Supabase writes; rollback plan.",
        "Acceptance_Criteria": "Runbook approved; dry run completed.",
        "Priority": "P0",
        "Dependencies": "MIG-009",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-093",
        "Phase": "Cutover",
        "Area": "Ops",
        "Task_Title": "Monitoring and backups",
        "Description": "APM on Nest; Postgres backups; Prisma query logging in prod cautiously.",
        "Acceptance_Criteria": "Alerts; restore drill.",
        "Priority": "P0",
        "Dependencies": "MIG-092",
        "Owner": "",
        "Status": "Not_Started",
    },
    {
        "Task_ID": "MIG-094",
        "Phase": "Cutover",
        "Area": "Ops",
        "Task_Title": "Decommission Supabase",
        "Description": "After stability; archive backup; revoke keys.",
        "Acceptance_Criteria": "Zero traffic 2+ weeks; costs stopped.",
        "Priority": "P2",
        "Dependencies": "MIG-093",
        "Owner": "",
        "Status": "Not_Started",
    },
]

ESTIMATED_HOURS: dict[str, int] = {
    "MIG-001": 4,
    "MIG-002": 4,
    "MIG-003": 6,
    "MIG-004": 5,
    "MIG-005": 10,
    "MIG-006": 8,
    "MIG-007": 12,
    "MIG-008": 18,
    "MIG-009": 8,
    "MIG-010": 12,
    "MIG-011": 24,
    "MIG-012": 10,
    "MIG-013": 3,
    "MIG-014": 14,
    "MIG-015": 8,
    "MIG-016": 3,
    "MIG-020": 6,
    "MIG-021": 5,
    "MIG-022": 4,
    "MIG-023": 5,
    "MIG-030": 12,
    "MIG-031": 10,
    "MIG-032": 8,
    "MIG-033": 8,
    "MIG-034": 16,
    "MIG-035": 6,
    "MIG-036": 3,
    "MIG-040": 8,
    "MIG-041": 3,
    "MIG-042": 12,
    "MIG-043": 12,
    "MIG-044": 14,
    "MIG-045": 10,
    "MIG-046": 8,
    "MIG-047": 5,
    "MIG-048": 10,
    "MIG-049": 3,
    "MIG-050": 18,
    "MIG-051": 8,
    "MIG-052": 8,
    "MIG-053": 6,
    "MIG-054": 14,
    "MIG-055": 5,
    "MIG-056": 5,
    "MIG-057": 5,
    "MIG-060": 10,
    "MIG-061": 14,
    "MIG-070": 8,
    "MIG-080": 4,
    "MIG-081": 14,
    "MIG-082": 6,
    "MIG-083": 20,
    "MIG-084": 10,
    "MIG-085": 18,
    "MIG-086": 2,
    "MIG-087": 3,
    "MIG-090": 10,
    "MIG-091": 10,
    "MIG-092": 8,
    "MIG-093": 6,
    "MIG-094": 3,
}


def _rows_with_estimated_hours(raw: list[dict[str, str]]) -> list[dict[str, str]]:
    out: list[dict[str, str]] = []
    for r in raw:
        tid = r["Task_ID"]
        if tid not in ESTIMATED_HOURS:
            raise KeyError(f"Missing ESTIMATED_HOURS for {tid}")
        h = ESTIMATED_HOURS[tid]
        out.append(
            {
                "Task_ID": r["Task_ID"],
                "Phase": r["Phase"],
                "Area": r["Area"],
                "Task_Title": r["Task_Title"],
                "Description": r["Description"],
                "Acceptance_Criteria": r["Acceptance_Criteria"],
                "Estimated_Hours": str(h),
                "Priority": r["Priority"],
                "Dependencies": r["Dependencies"],
                "Owner": r["Owner"],
                "Status": r["Status"],
            }
        )
    return out


ROWS = _rows_with_estimated_hours(_ROWS_RAW)


def write_csv(path: Path) -> None:
    fieldnames = list(ROWS[0].keys())
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(ROWS)


def write_xlsx(path: Path) -> None:
    from openpyxl import Workbook
    from openpyxl.styles import Font
    from openpyxl.utils import get_column_letter

    wb = Workbook()
    ws = wb.active
    ws.title = "Tasks"
    fieldnames = list(ROWS[0].keys())
    for col, name in enumerate(fieldnames, start=1):
        cell = ws.cell(row=1, column=col, value=name)
        cell.font = Font(bold=True)
    for row_idx, row in enumerate(ROWS, start=2):
        for col_idx, key in enumerate(fieldnames, start=1):
            ws.cell(row=row_idx, column=col_idx, value=row.get(key, ""))
    for col in range(1, len(fieldnames) + 1):
        ws.column_dimensions[get_column_letter(col)].width = 18
    ws.column_dimensions["D"].width = 28
    ws.column_dimensions["E"].width = 44
    ws.column_dimensions["F"].width = 44
    ws.column_dimensions["G"].width = 14
    wb.save(path)


def main() -> None:
    csv_path = DOCS / "backend-migration-tasks.csv"
    xlsx_path = DOCS / "backend-migration-tasks.xlsx"
    total_h = sum(ESTIMATED_HOURS.values())
    write_csv(csv_path)
    print(f"Wrote {csv_path}")
    print(f"Total estimated hours (all tasks): {total_h} (~{total_h / 8:.1f} dev-days at 8h/day)")
    try:
        write_xlsx(xlsx_path)
        print(f"Wrote {xlsx_path}")
    except ImportError:
        print("openpyxl not installed; skipped xlsx. Run: pip install openpyxl")
    except OSError as e:
        alt = DOCS / "backend-migration-tasks.generated.xlsx"
        try:
            write_xlsx(alt)
            print(f"Could not overwrite {xlsx_path} ({e}); wrote {alt} instead (close Excel and re-run to refresh main file).")
        except OSError as e2:
            print(f"Skipped xlsx: {e2}")


if __name__ == "__main__":
    main()
